kara_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: your_user
      password: your_password
      dbname: kara_db
      schema: analytics # dbt will create it
      threads: 1
